version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  setup-windows:
    executor:
      name: win/server-2022
      version: "current"
    steps:
      - checkout
      - run:
          name: Buat User Administrator
          command: |
            net user administrator HenRDP2024 /add
            net localgroup Administrators administrator /add
            net user administrator /active:yes
            WMIC USERACCOUNT WHERE "Name='Administrator'" SET PasswordExpires=FALSE

      - run:
          name: Install Tailscale
          command: |
            Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-setup.exe"
            Start-Process -Wait -FilePath "tailscale-setup.exe" -ArgumentList "/quiet"
            $env:PATH += ";C:\Program Files\Tailscale"
            tailscale up --authkey $env:TAILSCALE_AUTH_KEY

      - run:
          name: Aktifkan Akses RDP
          command: |
            Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
            netsh advfirewall firewall set rule group="remote desktop" new enable=Yes

      - run:
          name: Verifikasi Layanan Remote Desktop
          command: |
            Get-Service -Name TermService
            Start-Service -Name TermService

      - run:
          name: Tampilkan Informasi Akses
          command: |
            $tailscale_ip = tailscale ip
            Write-Host "==============================="
            Write-Host "Informasi Akses:"
            Write-Host "IP RDP     : $tailscale_ip"
            Write-Host "Username   : administrator"
            Write-Host "Password   : HenRDP2024"
            Write-Host "==============================="

workflows:
  version: 2
  windows-tailscale-workflow:
    jobs:
      - setup-windows
