version: 2.1

# Menggunakan Windows Orb untuk mempermudah setup
orbs:
  win: circleci/windows@5.0

jobs:
  setup-windows:
    executor:
      name: win/server-2022
      version: "current"
    steps:
      - checkout
      - run:
          name: Buat User Administrator
          command: |
            net user HenCoders HenCoders2024 /add
            net localgroup Administrators HenCoders /add
            net user HenCoders /active:yes
            WMIC USERACCOUNT WHERE "Name='HenCoders'" SET PasswordExpires=FALSE

      - run:
          name: Instal Tailscale
          command: |
            Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup.exe" -OutFile "tailscale-setup.exe"
            Start-Process -Wait -FilePath "tailscale-setup.exe" -ArgumentList "/quiet"
            tailscale up --authkey $TAILSCALE_AUTH_KEY
            $tailscale_ip = tailscale ip
            Set-Content -Path tailscale_ip.txt -Value $tailscale_ip

      - run:
          name: Aktifkan Akses RDP
          command: |
            Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
            netsh advfirewall firewall set rule group="remote desktop" new enable=Yes

      - run:
          name: Aktifkan Audio
          command: |
            sc config Audiosrv start= auto
            net start Audiosrv
            sc config AudioEndpointBuilder start= auto
            net start AudioEndpointBuilder

      - run:
          name: Tampilkan Informasi Akses
          command: |
            $tailscale_ip = Get-Content tailscale_ip.txt
            Write-Host "==============================="
            Write-Host "Informasi Akses:"
            Write-Host "IP RDP     : $tailscale_ip"
            Write-Host "Username   : HenCoders"
            Write-Host "Password   : HenCoders2024"
            Write-Host "==============================="

      - run:
          name: Menjaga Sesi Tetap Aktif
          command: |
            Write-Host "Menjaga sesi tetap aktif..."
            while ($true) {
              Start-Sleep -Seconds 300
              Write-Host "Sesi masih aktif..."

workflows:
  version: 2
  windows-tailscale-workflow:
    jobs:
      - setup-windows
