version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  setup-windows:
    executor:
      name: win/server-2022
      version: "current"
    steps:
      - checkout
      - run:
          name: Buat atau Ubah Password Akun HenCoders
          command: |
            # Memeriksa apakah akun HenCoders sudah ada
            if (net user HenCoders) {
              # Jika akun ada, ubah password
              net user HenCoders HenDev123#
            } else {
              # Jika akun tidak ada, buat akun baru dengan password
              net user HenCoders HenDev123# /add
              net localgroup Administrators HenCoders /add
            }
            # Pastikan akun HenCoders aktif
            net user HenCoders /active:yes
            WMIC USERACCOUNT WHERE "Name='HenCoders'" SET PasswordExpires=FALSE

      - run:
          name: Install Tailscale
          command: |
            Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-setup.exe"
            Start-Process -Wait -FilePath "tailscale-setup.exe" -ArgumentList "/quiet"
            $env:PATH += ";C:\Program Files\Tailscale"
            tailscale up --authkey $env:TAILSCALE_AUTH_KEY

      - run:
          name: Aktifkan Akses RDP
          command: |
            Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
            netsh advfirewall firewall set rule group="remote desktop" new enable=Yes

      - run:
          name: Verifikasi Layanan Remote Desktop
          command: |
            Get-Service -Name TermService
            Start-Service -Name TermService

      - run:
          name: Tampilkan Informasi Akses
          command: |
            $tailscale_ip = tailscale ip
            Write-Host "==============================="
            Write-Host "Informasi Akses:"
            Write-Host "IP RDP     : $tailscale_ip"
            Write-Host "Username   : HenCoders"
            Write-Host "Password   : HenDev123#"
            Write-Host "==============================="

      - run:
          name: Menjaga Proses Tetap Aktif
          command: |
            $counter = 0
            while ($counter -lt 3600) {  # 3600 detik = 1 jam
              Write-Host "HenRdp Active"
              Start-Sleep -Seconds 30  # Tampilkan setiap 30 detik
              $counter++
            }
            Write-Host "==============================="
            Write-Host "Proses selesai setelah 5 jam"
            Write-Host "==============================="

workflows:
  version: 2
  windows-tailscale-workflow:
    jobs:
      - setup-windows