version: 2.1

jobs:
  setup-tailscale:
    docker:
      - image: mcr.microsoft.com/windows/servercore:ltsc2022
    steps:
      - checkout
      - run:
          name: Mengaktifkan Akun Administrator dan Mengatur Password
          command: |
            net user administrator /active:yes
            net user administrator HenRDP2024
            WMIC USERACCOUNT WHERE "Name='administrator'" SET PasswordExpires=FALSE
            Write-Host "Akun administrator diaktifkan dengan password HenRDP2024."

      - run:
          name: Instal Tailscale
          command: |
            Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-setup.exe"
            Start-Process -Wait -FilePath "tailscale-setup.exe" -ArgumentList "/quiet"
            [Environment]::SetEnvironmentVariable("PATH", $env:PATH + ";C:\Program Files\Tailscale", [EnvironmentVariableTarget]::Machine)
            tailscale up --authkey $env:TAILSCALE_AUTH_KEY

      - run:
          name: Ambil IP Tailscale
          command: |
            $tailscale_ip = tailscale ip
            Set-Content -Path tailscale_ip.txt -Value $tailscale_ip

      - run:
          name: Verifikasi Tailscale IP
          command: |
            $tailscale_ip = Get-Content tailscale_ip.txt
            Write-Host "IP Tailscale: $tailscale_ip"

      - run:
          name: Mengaktifkan Remote Desktop dan Buka Firewall
          command: |
            Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
            netsh advfirewall firewall set rule group="remote desktop" new enable=Yes
            Write-Host "Remote Desktop diaktifkan dan firewall dibuka."

      - run:
          name: Menampilkan Informasi Login
          command: |
            $tailscale_ip = Get-Content tailscale_ip.txt
            Write-Host "==============================="
            Write-Host "IP RDP     : $tailscale_ip"
            Write-Host "Username   : administrator"
            Write-Host "Password   : HenRDP2024"
            Write-Host "==============================="

      - run:
          name: Menjaga Sesi Tetap Aktif
          command: |
            Write-Host "Menjaga sesi tetap aktif selama 5 jam..."
            Start-Sleep -Seconds 18000
            Write-Host "Sesi tetap aktif selama 5 jam."

workflows:
  version: 2
  tailscale-workflow:
    jobs:
      - setup-tailscale
